name: android-armv8-cpu

on:
  push:
    branches: [tengine-lite]
    paths:
    - '.github/workflows/android-armv8-cpu.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'source/*'
    - 'source/api/*'
    - 'source/executer/*'
    - 'source/graph/*'
    - 'source/module/*'
    - 'source/operator/*'
    - 'source/optimizer/*'
    - 'source/scheduler/*'
    - 'source/serializer/*'
    - 'source/system/*'
    - 'source/utility/*'
    - 'source/device/cpu/**'
  pull_request:
    branches: [tengine-lite]
    paths:
    - '.github/workflows/android-armv8-cpu.yml'
    - 'CMakeLists.txt'
    - 'cmake/**'
    - 'source/*'
    - 'source/api/*'
    - 'source/executer/*'
    - 'source/graph/*'
    - 'source/module/*'
    - 'source/operator/*'
    - 'source/optimizer/*'
    - 'source/scheduler/*'
    - 'source/serializer/*'
    - 'source/system/*'
    - 'source/utility/*'
    - 'source/device/cpu/**'

jobs:
  android-armv8-cpu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_HOME/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM=android-21 ..
    - name: build
      run: cmake --build build -j 2
